"""
This type stub file was generated by pyright.
"""
from pathlib import Path


class PackageNotFoundError(KeyError):
    ...


def get_package_share_path(package_name: str, print_warning: bool = True) -> Path:
    ...
