"""
This type stub file was generated by pyright.
"""
import builtin_interfaces.msg
import rosgraph_msgs.msg


class Header:
    """Message class 'Header'."""
    stamp: builtin_interfaces.msg.Time
    frame_id: str
