"""
This type stub file was generated by pyright.
"""


class RcutilsLogger:
    def debug(self, message: str) -> bool:
        """Log a message with `DEBUG` severity via :py:classmethod:RcutilsLogger.log:."""
        ...

    def info(self, message: str) -> bool:
        """Log a message with `INFO` severity via :py:classmethod:RcutilsLogger.log:."""
        ...

    def warning(self, message: str) -> bool:
        """Log a message with `WARN` severity via :py:classmethod:RcutilsLogger.log:."""
        ...

    def warn(self, message: str) -> bool:
        """
        Log a message with `WARN` severity via :py:classmethod:RcutilsLogger.log:.

        Deprecated in favor of :py:classmethod:RcutilsLogger.warning:.
        """
        ...

    def error(self, message: str) -> bool:
        """Log a message with `ERROR` severity via :py:classmethod:RcutilsLogger.log:."""
        ...

    def fatal(self, message: str) -> bool:
        """Log a message with `FATAL` severity via :py:classmethod:RcutilsLogger.log:."""
        ...
