"""
This type stub file was generated by pyright.
"""

from typing import Any, Type


def serialize_message(message: Any) -> bytes:
    ...


def deserialize_message(serialized_message: bytes, message_type: Type[Any]) -> Any:
    ...
