"""
This type stub file was generated by pyright.
"""


from typing import Any, Callable, Iterable


class SimpleFilter:
    def __init__(self) -> None:
        ...

    def registerCallback(self, cb: Callable[..., None], *args: Any) -> int:
        ...

    def signalMessage(self, *msg: Any) -> None:
        ...


class TimeSynchronizer(SimpleFilter):
    def __init__(self, fs, queue_size) -> None:
        ...

    def connectInput(self, fs):  # -> None:
        ...

    def add(self, msg, my_queue, my_queue_index=...):  # -> None:
        ...


class ApproximateTimeSynchronizer(TimeSynchronizer):

    def __init__(self, fs: Iterable[SimpleFilter], queue_size, slop, allow_headerless=...) -> None:
        ...

    def add(self, msg, my_queue, my_queue_index=...):  # -> None:
        ...
