"""
This type stub file was generated by pyright.
"""


class ReconfigurationAnnouncement_Request:
    ...


class ReconfigurationAnnouncement_Response:
    ...


class ReconfigurationAnnouncement:
    Request = ReconfigurationAnnouncement_Request
    Response = ReconfigurationAnnouncement_Response
